version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/beefstar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      - postgresql
  postgresql:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=beefstar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DOCKER_ENV=true
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  angular-app:
    build:
      context: ./Front
    ports:
      - "4200:4200"
    depends_on:
      - backend
networks:
  spring-boot-postgres:
volumes:
  db-data:
